const COMMIT_RANGE = 7;
const CROSSTITCH_SPEC = 20;
const CROSSTITCH_DEFAULT_COLOR = "oklch(44.6% 0.043 257.281)";
const CROSSTITCH_DEFAULT_SELECT_COLOR = "#000000";

export {
  COMMIT_RANGE,
  CROSSTITCH_SPEC,
  CROSSTITCH_DEFAULT_COLOR,
  CROSSTITCH_DEFAULT_SELECT_COLOR,
};
